name: "Read README file from PR"

on:
  issue_comment:
    types: [created]

jobs:
  read-readme:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/readme')
    steps:
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch

    - name: Checkout PR branch
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.comment-branch.outputs.head_ref }}
        
    - name: Read README.md
      id: readme
      uses: juliangruber/read-file-action@v1
      with:
        path: ./README.md
        
    - name: Echo README.md content
      run: echo "${{ steps.readme.outputs.content }}"

    - name: React to comment
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ github.event.comment.id }},
            content: 'rocket'
          })
